<a href="https://colab.research.google.com/github/jboverio/Data-Science-Walks/blob/main/shuffling_vs_no_shuffling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
# Create a synthetic dataset
X, y = make_classification(n_samples=1000, n_features=20, n_informative=2, n_redundant=10, random_state=42)

# Sort the data by target variable
sorted_idxs = np.argsort(y)
X_sorted, y_sorted = X[sorted_idxs], y[sorted_idxs]

# Split the sorted data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X_sorted, y_sorted, test_size=0.2, random_state=42)

# Train a logistic regression model on the sorted data
model = LogisticRegression()
model.fit(X_train, y_train)

# Evaluate the model on the training set
y_train_pred = model.predict(X_train)
print("Accuracy on training set without shuffling: ", accuracy_score(y_train, y_train_pred))

# Evaluate the model on the test set
y_test_pred = model.predict(X_test)
print("Accuracy on test set without shuffling: ", accuracy_score(y_test, y_test_pred))

# Now let's shuffle the data
X_shuffled, y_shuffled = shuffle(X_sorted, y_sorted, random_state=42)

# Split the shuffled data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X_shuffled, y_shuffled, test_size=0.2, random_state=42)

# Train a logistic regression model on the shuffled data
model = LogisticRegression()
model.fit(X_train, y_train)

# Evaluate the model on the training set
y_train_pred = model.predict(X_train)
print("Accuracy on training set with shuffling: ", accuracy_score(y_train, y_train_pred))

# Evaluate the model on the test set
y_test_pred = model.predict(X_test)
print("Accuracy on test set with shuffling: ", accuracy_score(y_test, y_test_pred))

Accuracy on training set without shuffling:  0.86125
Accuracy on test set without shuffling:  0.845
Accuracy on training set with shuffling:  0.85875
Accuracy on test set with shuffling:  0.885

In [9]:
import pandas as pd
pd.DataFrame(y_sorted)
#this causes the model to overfit on the data

     0
0    0
1    0
2    0
3    0
4    0
..  ..
995  1
996  1
997  1
998  1
999  1

[1000 rows x 1 columns]